### ISSUE TITLE
How to clear deleted containers? 

### ISSUE THREAD

**Issue by zhong-ys** [thin-edge/tedge-container-plugin#49]
I had some exited containers inside the Raspberry Pi. After installing this container plugin, they all showed up on the platform. I have deleted them from the hardware but they still exist on the platform. 

I can see that there are retained mqtt messages in the thin-edge's broker. Is sending a blank message to each service topic the only way to delete them on the platform? Is there a smarter way to delete them or keep the container list up to date? 

(Containers in the screenshot no longer exist)
<img width="852" alt="Screenshot 2024-09-24 at 16 25 22" src="https://github.com/user-attachments/assets/b9402010-8dd6-46e1-9e9a-0b9bf0bfcd77">

**Comment by reubenmiller** [comment]
Technically deleting the container's "should" be fairly easy,  though it is probably more involved than desired (we want to add some more convenient way to do this in thin-edge.io), but the docs are here for now: 

https://thin-edge.github.io/thin-edge.io/operate/registration/deregister/

However, I think we're reaching the limit of the container and container-group scripts (as they are written in posix shell)...it might be time that we start rewriting these elements using either Rust or golang (I would prefer golang in this case as it can re-use the official docker libs as they are also written in go).

**Comment by zhong-ys** [comment]
Thank you Reuben!

**Comment by reubenmiller** [comment]
There is some ongoing work which is looking at porting the monitoring part to a golang application which would support deleting services via thin-edge.io's Cumulocity local proxy.

The work is being done here, https://github.com/reubenmiller/tedge-container-monitor, but it might find its way back to this repo once the design is proven first.
